'use strict';mix_d("BuffetDisclaimersCards__buffet-disclaimers-card:buffet-disclaimers-card__tefdhkXt","require exports tslib @c/remote-operations @c/scoped-dom @c/aui-utils @c/metrics".split(" "),function(ja,U,t,ka,la,K,ma){function V(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function na(a){if(a&&a.__esModule)return a;var b=Object.create(null);a&&Object.keys(a).forEach(function(c){if("default"!==c){var d=Object.getOwnPropertyDescriptor(a,c);Object.defineProperty(b,c,d.get?d:
{enumerable:!0,get:function(){return a[c]}})}});b["default"]=a;return b}var oa=V(ka),n=V(la),W;(function(a){a.BEFORE_FIRST_OPEN="before first open";a.OPEN="open";a.CLOSE="close"})(W||(W={}));var X;(function(a){a.RIGHT_OUT_OF_SCREEN="-120%";a.INSIDE_SCREEN="0px"})(X||(X={}));var u;(function(a){a.MOBILE="mobile";a.DESKTOP="desktop"})(u||(u={}));var v;(function(a){a.ATF="ATF";a.BTF="BTF"})(v||(v={}));var Y;(function(a){a.FATAL="FATAL";a.ERROR="ERROR";a.WARN="WARN"})(Y||(Y={}));var w;(function(a){a[a.PSI=
0]="PSI";a[a.RSP_MANUFACTURER=1]="RSP_MANUFACTURER"})(w||(w={}));var g;(function(a){a.CLIENT_LOAD="Buffet.Client.Load";a.INGRESS_LINK_CLICK="Buffet.Sidesheet.IngressLinkClick";a.SIDESHEET_OPENED="Buffet.Sidesheet.Open";a.SIDESHEET_CLOSED="Buffet.Sidesheet.Close";a.SIDESHEET_DWELL_TIME="Buffet.Sidesheet.DwellTime";a.SIDESHEET_CONTENT_LOADED="Buffet.SdesheetContent.Load";a.SIDESHEET_CONTENT_LOAD_LATENCY="Buffet.SidesheetContent.LoadLatency";a.PSI_PILL_CLICK="Buffet.SidesheetContent.PsiPillClick";a.MANUFACTURER_PILL_CLICK=
"Buffet.SidesheetContent.ManufacturerPillClick";a.RSP_PILL_CLICK="Buffet.SidesheetContent.RspPillClick";a.PSI_ZOOM_IN_CLICK="Buffet.SidesheetContent.PsiZoomInClick";a.PSI_ZOOM_OUT_CLICK="Buffet.SidesheetContent.PsiZoomOutClick";a.MISSING_ASIN_ERROR="Buffet.MissingAsin.Error";a.MISSING_CRUCIAL_ELEMENTS_ERROR="Buffet.MissingCrucialElements.Error";a.MISSING_GPSR_CONTENT_ERROR="Buffet.MissingGpsrContent.Error";a.SIDESHEET_OPEN_ERROR="Buffet.Sidesheet.Open.Error";a.SIDESHEET_CONTENT_LOAD_ERROR="Buffet.Sidesheet.ContentLoad.Error";
a.ALL_AAPI_CALL_FAIL="Buffet.AllAapiCall.FAIL";a.RSP_MANUFACTURER_AAPI_CALL_FAIL="Buffet.RspManufacturerAapiCall.FAIL";a.PSI_AAPI_CALL_FAIL="Buffet.PsiAapiCall.FAIL"})(g||(g={}));var L=function(a,b){a&&!a.classList.contains(b)&&a.classList.add(b)},M=function(a,b){a&&a.classList.contains(b)&&a.classList.remove(b)},I=function(a){if(!a.every(function(b){return b})||!a.map(function(b){return b.id}).every(function(b){return b}))throw Error("Some HTML elements are missing.");},Z=function(a){return{html:a.innerHTML,
className:a.className,style:a.style.cssText}},N=function(a,b){a.innerHTML=b.html;a.className=b.className;a.style.cssText=b.style},x;(function(a){a.LANDING_ASIN="buffet-btf-asin";a.OPEN_BUTTON_IMG_DOC_CONT="buffet-sidesheet-ingress";a.DISCLAIMER_CONTENT="buffet-disclaimer-content";a.CLOSE_BUTTON="buffet-sidesheet-close";a.DARKENED_BACKGROUND="buffet-darkened-background";a.SIDESHEET_ROOT="buffet-sidesheet-root";a.SIDESHEET="buffet-sidesheet";a.SIDESHEET_CONTENT="buffet-sidesheet-content";a.SIDESHEET_SUB_CONTENT=
"buffet-sidesheet-sub-content";a.SIDESHEET_CONTENT_BUFFER_SPINNER="buffet-sidesheet-content-spinner";a.SIDESHEET_ERROR_ALERT="buffet-sidesheet-error-alert";a.SIDESHEET_PILLS_CONTAINER="buffet-sidesheet-pills-container";a.SIDESHEET_RSP_PILL="buffet-sidesheet-rsp-pill";a.SIDESHEET_MANUFACTURER_PILL="buffet-sidesheet-manufacturer-pill";a.SIDESHEET_PSI_PILL="buffet-sidesheet-psi-pill";a.SIDESHEET_RSP_CONTENT="buffet-sidesheet-rsp-content-container";a.SIDESHEET_MANUFACTURER_CONTENT="buffet-sidesheet-manufacturer-content-container";
a.SIDESHEET_PSI_CONTENT="buffet-sidesheet-psi-content-container";a.SIDESHEET_PSI_CAROUSEL="buffet-psi-component";a.RSP_MANUFACTURER_AAPI_FAIL="buffet-sidesheet-rsp-manufacturer-aapi-fail";a.PSI_AAPI_FAIL="buffet-sidesheet-psi-aapi-fail"})(x||(x={}));var k=function(a,b,c,d){void 0===d&&(d=1);ma.count(a+"."+b+"."+c,d)},aa=function(a,b,c){if(a){var d=!1,h=a.querySelectorAll("li"),e=a.querySelectorAll("img");h.forEach(function(p,q){p.style.maxWidth="1600px";0===q?p.style.marginLeft="0px":q===h.length-
1&&(p.style.marginRight="0px")});e.forEach(function(p){p.addEventListener("click",function(){return t.__awaiter(void 0,void 0,void 0,function(){return t.__generator(this,function(q){switch(q.label){case 0:return d?(k(b,c,g.PSI_ZOOM_OUT_CLICK),h.forEach(function(l){l.style.width=""}),e.forEach(function(l){l.style.maxWidth="100%";var y=n["default"].cardRoot.querySelector("#"+l.id+"-zoomed-out").value;l.src=y}),d=!1):(k(b,c,g.PSI_ZOOM_IN_CLICK),h.forEach(function(l){l.style.width="1600px"}),e.forEach(function(l){l.style.maxWidth=
"1600px";var y=n["default"].cardRoot.querySelector("#"+l.id+"-zoomed-in").value;l.src=y}),d=!0),[4,p.decode()];case 1:return q.sent(),p.scrollIntoView({block:"center",inline:"center"}),[2]}})})})})}},ba;(function(a){a.SHOW="show";a.HIDE="hide";a.CLICK="click";a.BEFORE_SHOW="beforeShow";a.WEE_SHOW="weeShow";a.RSP_SHOW="rspShow"})(ba||(ba={}));var f;(function(a){a[a.RSP=0]="RSP";a[a.MANUFACTURER=1]="MANUFACTURER";a[a.PSI=2]="PSI"})(f||(f={}));var O=function(a,b,c){for(var d in f){var h=f[d];h===a?(L(b[h],
"a-button-selected"),M(c[h],"aok-hidden")):(M(b[h],"a-button-selected"),L(c[h],"aok-hidden"))}},pa=function(a,b){a.forEach(function(c){c.addEventListener("click",function(){var d=b.offsetWidth,h=b.scrollWidth,e=c.offsetLeft-d/2+c.offsetWidth/2;0>e?e=0:e+d>h&&(e=h-d);b.scroll({left:e,behavior:"smooth"})})})},Q,R,C=new Set(Object.values(w).filter(function(a){return"number"===typeof a})),r,m,ca=Object.keys(f).length/2,qa=Object.keys(w).length/2,ra=function(a,b,c,d,h,e,p,q,l,y){return t.__awaiter(void 0,
void 0,void 0,function(){var G,A,H,D,J,z,B,E;return t.__generator(this,function(F){switch(F.label){case 0:G=Date.now();a&&(a=!1,Q=Z(q),R=Z(l));if(b)return[3,6];F.label=1;case 1:F.trys.push([1,4,,5]);N(q,Q);N(l,R);A=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_SUB_CONTENT);H=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_PILLS_CONTAINER);r=Array(ca);m=Array(ca);r[f.RSP]=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_RSP_PILL);r[f.MANUFACTURER]=n["default"].cardRoot.querySelector("#"+
e.SIDESHEET_MANUFACTURER_PILL);r[f.PSI]=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_PSI_PILL);m[f.RSP]=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_RSP_CONTENT);m[f.MANUFACTURER]=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_MANUFACTURER_CONTENT);m[f.PSI]=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_PSI_CONTENT);try{I([A]),I([H]),I(r),I(m)}catch(da){throw k(c,d,g.MISSING_GPSR_CONTENT_ERROR),Error();}pa(r,H);O(f.PSI,r,m);r[f.RSP].addEventListener("click",function(){O(f.RSP,
r,m);k(c,d,g.RSP_PILL_CLICK)});r[f.MANUFACTURER].addEventListener("click",function(){O(f.MANUFACTURER,r,m);k(c,d,g.MANUFACTURER_PILL_CLICK)});r[f.PSI].addEventListener("click",function(){O(f.PSI,r,m);k(c,d,g.PSI_PILL_CLICK)});return[4,h.getPsiContent({asin:p})];case 2:return(D=F.sent())&&"false"===D.querySelector("#"+e.PSI_AAPI_FAIL).value?(C.delete(w.PSI),m[f.PSI].innerHTML=D.outerHTML,J=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_PSI_CAROUSEL),aa(J,c,d)):k(c,d,g.PSI_AAPI_CALL_FAIL),[4,h.getRspManufacturerContent({asin:p})];
case 3:(z=F.sent())&&"false"===z.querySelector("#"+e.RSP_MANUFACTURER_AAPI_FAIL).value?(C.delete(w.RSP_MANUFACTURER),B=z.querySelector("#"+e.SIDESHEET_RSP_CONTENT),E=z.querySelector("#"+e.SIDESHEET_MANUFACTURER_CONTENT),m[f.RSP].innerHTML=B.innerHTML,m[f.MANUFACTURER].innerHTML=E.innerHTML):k(c,d,g.RSP_MANUFACTURER_AAPI_CALL_FAIL);if(C.size===qa)throw k(c,d,g.ALL_AAPI_CALL_FAIL),Error();q.style.opacity="0";k(c,d,g.SIDESHEET_CONTENT_LOAD_LATENCY,Date.now()-G);K.delay(function(){L(q,"aok-hidden");M(A,
"aok-hidden");l.style.opacity="1"},200);b=!0;return[3,5];case 4:return F.sent(),k(c,d,g.SIDESHEET_CONTENT_LOAD_ERROR),N(q,Q),N(l,R),y=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_ERROR_ALERT),M(y,"aok-hidden"),q.style.opacity="0",K.delay(function(){L(q,"aok-hidden");l.style.opacity="1"},200),[3,5];case 5:return[3,7];case 6:0!==C.size&&C.forEach(function(da){return t.__awaiter(void 0,void 0,void 0,function(){var ea,S,fa,P,ha,ia;return t.__generator(this,function(T){switch(T.label){case 0:ea=
da;switch(ea){case w.PSI:return[3,1];case w.RSP_MANUFACTURER:return[3,3]}return[3,5];case 1:return[4,h.getPsiContent({asin:p})];case 2:return(S=T.sent())&&"false"===S.querySelector("#"+e.PSI_AAPI_FAIL).value?(C.delete(w.PSI),m[f.PSI].style.opacity="0",K.delay(function(){m[f.PSI].innerHTML=S.outerHTML;m[f.PSI].style.opacity="1"},500),fa=n["default"].cardRoot.querySelector("#"+e.SIDESHEET_PSI_CAROUSEL),aa(fa,c,d)):k(c,d,g.PSI_AAPI_CALL_FAIL),[3,5];case 3:return[4,h.getRspManufacturerContent({asin:p})];
case 4:return(P=T.sent())&&"false"===P.querySelector("#"+e.RSP_MANUFACTURER_AAPI_FAIL).value?(C.delete(w.RSP_MANUFACTURER),ha=P.querySelector("#"+e.SIDESHEET_RSP_CONTENT),ia=P.querySelector("#"+e.SIDESHEET_MANUFACTURER_CONTENT),m[f.RSP].style.opacity="0",m[f.MANUFACTURER].style.opacity="0",K.delay(function(){m[f.RSP].innerHTML=ha.innerHTML;m[f.MANUFACTURER].innerHTML=ia.innerHTML;m[f.RSP].style.opacity="1";m[f.MANUFACTURER].style.opacity="1"},500)):k(c,d,g.RSP_MANUFACTURER_AAPI_CALL_FAIL),[3,5];case 5:return[2]}})})}),
F.label=7;case 7:return[2,[a,b]]}})})};U._operationNames=[];U.card=function(){return t.__awaiter(void 0,void 0,void 0,function(){var a,b,c,d,h,e,p,q,l,y,G,A,H,D;return t.__generator(this,function(J){switch(J.label){case 0:k(u.DESKTOP,v.BTF,g.CLIENT_LOAD);a=n["default"].cardRoot.querySelector("#"+x.LANDING_ASIN);if(!a||!a.value)return k(u.DESKTOP,v.BTF,g.MISSING_ASIN_ERROR),[2];b=n["default"].cardRoot.querySelector("#"+x.OPEN_BUTTON_IMG_DOC_CONT);c=n["default"].cardRoot.querySelector("#"+x.SIDESHEET_CONTENT);
d=n["default"].cardRoot.querySelector("#"+x.DARKENED_BACKGROUND);h=n["default"].cardRoot.querySelector("#"+x.SIDESHEET_CONTENT_BUFFER_SPINNER);e=n["default"].cardRoot.querySelector("#"+x.SIDESHEET_ERROR_ALERT);p=n["default"].cardRoot.querySelector("#"+x.CLOSE_BUTTON);q=[b,c,d,h,e,p];try{I(q)}catch(z){return k(u.DESKTOP,v.BTF,g.MISSING_CRUCIAL_ELEMENTS_ERROR),[2]}return[4,new Promise(function(z,B){ja(["@p/buffet-sidesheet"],function(E){z(na(E))},B)})];case 1:return l=J.sent().default,y=oa["default"].setup(["getRspManufacturerContent",
"getPsiContent"]),G=!0,A=!1,b.addEventListener("click",function(z){return t.__awaiter(void 0,void 0,void 0,function(){var B;return t.__generator(this,function(E){switch(E.label){case 0:return z.preventDefault(),k(u.DESKTOP,v.BTF,g.INGRESS_LINK_CLICK),l.showSidesheet(),k(u.DESKTOP,v.BTF,g.SIDESHEET_OPENED),[4,ra(G,A,u.DESKTOP,v.BTF,y,x,a.value,h,c,e)];case 1:B=t.__read.apply(void 0,[E.sent(),2]);G=B[0];if(A=B[1])k(u.DESKTOP,v.BTF,g.SIDESHEET_CONTENT_LOADED),H=Date.now();return[2]}})})}),D=function(){l.closeSidesheet();
k(u.DESKTOP,v.BTF,g.SIDESHEET_CLOSED);A&&k(u.DESKTOP,v.BTF,g.SIDESHEET_DWELL_TIME,Date.now()-H)},p.addEventListener("click",function(){D()}),d.addEventListener("click",function(){D()}),[2]}})})}});
