'use strict';mix_d("ExportAlternativeWidgetCards__export-alternative-card-desktop:export-alternative-card-desktop__Q0GxsinM","exports tslib @c/remote-operations @c/tracking @p/jQuery @c/metrics @p/A".split(" "),function(E,F,u,J,K,k,L){function C(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var M=C(u),d=C(K),v=C(L),w;(function(a){a.US="ATVPDKIKX0DER";a.UK="A1F83G8C2ARO7P";a.DE="A1PA6795UKMFR9";a.FR="A13V1IB3VIYZZH";a.IT="APJ6JRA9NG5V4";a.ES="A1RKKUPIHCS9HS";a.JP="A1VC38T7YXB528";
a.AU="A39IBJ37TRP1C6";a.SG="A19VAU5U5O7RUS"})(w||(w={}));var l;(function(a){a.DETAIL_DESKTOP_OUT_OF_STOCK="#exports_desktop_outOfStock_buybox_export_alternative_widget_ingress_feature_div";a.DETAIL_DESKTOP_UNQUALIFIED="#exports_desktop_unqualifiedBuybox_export_alternative_widget_ingress_feature_div";a.DETAIL_DESKTOP_UNDELIVERABLE="#exports_desktop_undeliverable_buybox_cta_feature_div";a.DETAIL_MOBILE_OUT_OF_STOCK="#exports_mobile_outOfStock_buybox_export_alternative_widget_ingress_feature_div";a.DETAIL_MOBILE_UNQUALIFIED=
"#exports_mobile_unqualifiedBuybox_export_alternative_widget_ingress_feature_div";a.DETAIL_MOBILE_UNDELIVERABLE="#exports_mobile_undeliverable_buybox_cta_feature_div";a.DETAIL_MOBILEAPP_OUT_OF_STOCK="#exports_mobileapp_outOfStock_buybox_export_alternative_widget_ingress_feature_div";a.DETAIL_MOBILEAPP_UNQUALIFIED="#exports_mobileapp_unqualifiedBuybox_export_alternative_widget_ingress_feature_div";a.DETAIL_MOBILEAPP_UNDELIVERABLE="#exports_mobileapp_undeliverable_buybox_cta_feature_div";a.GSOD_DESKTOP_OUT_OF_STOCK=
"#outOfStockBuyBox_feature_div";a.GSOD_DESKTOP_UNQUALIFIED="#unqualifiedBuyBox_feature_div";a.GSOD_DESKTOP_UNDELIVERABLE="#exportAlternativeWidget_feature_div";a.GSOD_MOBILE_UNQUALIFIED="#unqualified_feature_div";a.TEST="#exportAlternativeWidgetTestMarker"})(l||(l={}));var z;(function(a){a.DISABLED_ATC="#exports-buybox-disabled-atc";a.SEE_ALL_BUYING_OPTIONS="#buybox-see-all-buying-choices"})(z||(z={}));var y;(function(a){a.AOK_HIDDEN="aok-hidden";a.A_BUTTON_BASE="a-button-base";a.A_BUTTON_PRIMARY=
"a-button-primary"})(y||(y={}));var m;(function(a){a.TRIGGER_BUTTON="#exportAlternativeTriggerButton";a.TRIGGER_CONTENT=".export-alternative-trigger-content";a.MODAL_PRELOAD="#a-popover-exportAlternativeModal";a.SHEET_PRELOAD="#exportAlternativeSheetPreloadContent";a.ASINS_INFO="#exportAlternativeAsinsInfo";a.CONTENT_TITLE="#exportAlternativeContentTitle";a.COUNTRY_CODE="#exportAlternativeShipToCountryCode";a.COUNTRY_NAME="#exportAlternativeShipToCountryName";a.MARKETPLACE_ID="#exportAlternativeMarketplaceId";
a.IMPORT_FEE_ROW="#exportAlternativeImportFeeRow";a.ENERGY_EFFICIENCY_ROW="#exportAlternativeEnergyEfficiencyRow"})(m||(m={}));var A;(function(a){a.A_SIZE_MICRO="a-size-micro";a.A_SIZE_SMALL="a-size-small"})(A||(A={}));var B;(function(a){a.ENERGY_EFFICIENCY_CONTAINER=".energyEfficiencyContainer";a.ENERGY_EFFICIENCY_FICHE_LABEL=".energyEfficiencyProductFicheLabel"})(B||(B={}));var r;(function(a){a.DETAIL_OUT_OF_STOCK="detail_out_of_stock";a.DETAIL_UNQUALIFIED="detail_unqualified";a.DETAIL_UNDELIVERABLE=
"detail_undeliverable";a.E2E_TEST="e2e_test";a.TEST="test"})(r||(r={}));var G;(function(a){a.PRODUCT_API_ERROR="productApiError";a.ITEM_NOT_BUYABLE="itemNotBuyable";a.ITEM_NO_IMPORT_DETAILS="itemNoImportDetails";a.ITEM_NOT_DELIVERABLE="itemNotDeliverable";a.ITEM_MISSING_INFO="itemMissingInfo";a.PRICE_WRONG_FORMAT="priceWrongFormat";a.AGG_ERROR="aggregatedError";a.WEBLAB_ERROR="unknownTreatment"})(G||(G={}));var H;(function(a){a.FREE_SHIPPING="FREE_SHIPPING";a.UPSELL="UPSELL";a.NONE="NONE"})(H||(H=
{}));var h;(function(a){a.GET_CONTENT="exportAlternativeWidgetGetContent";a.TRIGGER_SHOW="exportAlternativeWidgetTriggerShow";a.TRIGGER_CLICK="exportAlternativeWidgetTriggerClick";a.VARIANT_DETAIL_OUT_OF_STOCK="exportAlternativeWidgetVariantDetailOutOfStock";a.VARIANT_DETAIL_UNDELIVERABLE="exportAlternativeWidgetVariantDetailUndeliverable";a.VARIANT_DETAIL_UNQUALIFIED="exportAlternativeWidgetVariantDetailUnqualified";a.VARIANT_NOT_FOUND="exportAlternativeWidgetVariantNotFound";a.CONTENT_SUCCESS="exportAlternativeWidgetContentSuccess";
a.CONTENT_FAILURE="exportAlternativeWidgetContentFailure";a.ITEM_COUNT="exportAlternativeWidgetItemCount";a.ITEM_CLICK="exportAlternativeWidgetItemClick";a.IMPORT_FEE_DEPOSIT_ROW_SHOW="exportAlternativeWidgetImportFeeDepositRowShow";a.ENERGY_EFFICIENCY_LABEL_SHOW="exportAlternativeWidgetEnergyEfficiencyLabelShow";a.ENERGY_EFFICIENCY_LABEL_CLICK="exportAlternativeWidgetEnergyEfficiencyLabelClick";a.ATC_CLICK="exportAlternativeWidgetAtcClick";a.ATC_SUCCESS="exportAlternativeWidgetAtcSuccess";a.ATC_FAILURE=
"exportAlternativeWidgetAtcFailure";a.MOBILE_POSTFIX="Mobile";a.EAW_ELIGIBLE_WHILE_ATC_ENABLED="exportAlternativeWidgetEligibleWhileATCEnabled"})(h||(h={}));u={};u[w.US]={showImportFeeDepositAndTotalLandingCost:!0};u[w.UK]={showEnergyEfficiency:!0};u[w.DE]={showEnergyEfficiency:!0};u[w.ES]={showEnergyEfficiency:!0};u[w.FR]={showEnergyEfficiency:!0};u[w.IT]={showEnergyEfficiency:!0};u;var N=function(a){var f=d["default"](m.TRIGGER_BUTTON),e=d["default"](m.IMPORT_FEE_ROW),c=d["default"](m.ENERGY_EFFICIENCY_ROW),
b=a?h.MOBILE_POSTFIX:"";f.length&&(k.count(h.TRIGGER_SHOW+b,1),f.click(function(){return k.count(h.TRIGGER_CLICK+b,1)}));e.length&&k.count(h.IMPORT_FEE_DEPOSIT_ROW_SHOW+b,1);c.length&&(k.count(h.ENERGY_EFFICIENCY_LABEL_SHOW+b,1),c.click(function(){return k.count(h.ENERGY_EFFICIENCY_LABEL_CLICK+b,1)}))},O=function(){var a=d["default"](l.GSOD_DESKTOP_OUT_OF_STOCK).length||d["default"](l.DETAIL_DESKTOP_OUT_OF_STOCK).length||d["default"](l.DETAIL_MOBILE_OUT_OF_STOCK).length||d["default"](l.DETAIL_MOBILEAPP_OUT_OF_STOCK).length,
f=d["default"](l.GSOD_DESKTOP_UNQUALIFIED).length||d["default"](l.GSOD_MOBILE_UNQUALIFIED).length||d["default"](l.DETAIL_DESKTOP_UNQUALIFIED).length||d["default"](l.DETAIL_MOBILE_UNQUALIFIED).length||d["default"](l.DETAIL_MOBILEAPP_UNQUALIFIED).length,e=d["default"](l.GSOD_DESKTOP_UNDELIVERABLE).length||d["default"](l.DETAIL_DESKTOP_UNDELIVERABLE).length||d["default"](l.DETAIL_MOBILE_UNDELIVERABLE).length||d["default"](l.DETAIL_MOBILEAPP_UNDELIVERABLE).length;if(a)return k.count(h.VARIANT_DETAIL_OUT_OF_STOCK,
1),r.DETAIL_OUT_OF_STOCK;if(f)return k.count(h.VARIANT_DETAIL_UNQUALIFIED,1),r.DETAIL_UNQUALIFIED;if(e)return k.count(h.VARIANT_DETAIL_UNDELIVERABLE,1),r.DETAIL_UNDELIVERABLE;if(d["default"](l.TEST).length)return r.E2E_TEST;k.count(h.VARIANT_NOT_FOUND,1)},P=function(a,f,e){if(f===r.E2E_TEST)d["default"](e?m.SHEET_PRELOAD:m.MODAL_PRELOAD).html('<span class="export-alternative-test-content-success"/>');else{if(f===r.DETAIL_UNDELIVERABLE){if(0===d["default"](z.DISABLED_ATC).length){k.count(h.EAW_ELIGIBLE_WHILE_ATC_ENABLED,
1);return}a.outerHTML||d["default"](z.DISABLED_ATC).removeClass(y.AOK_HIDDEN)}a.outerHTML&&(f===r.DETAIL_UNQUALIFIED&&d["default"](z.SEE_ALL_BUYING_OPTIONS).removeClass(y.A_BUTTON_PRIMARY).addClass(y.A_BUTTON_BASE),f=d["default"](e?m.SHEET_PRELOAD:m.MODAL_PRELOAD),f.html(a.outerHTML),d["default"](m.TRIGGER_CONTENT).removeClass(y.AOK_HIDDEN),N(e),e&&f.length&&f.find(B.ENERGY_EFFICIENCY_CONTAINER).each(function(c,b){c=d["default"](b).find(B.ENERGY_EFFICIENCY_FICHE_LABEL).first();c.hasClass(A.A_SIZE_SMALL)&&
c.removeClass(A.A_SIZE_SMALL).addClass(A.A_SIZE_MICRO)}))}},Q=function(a,f){var e,c,b,g,p=JSON.stringify(null!==(e=d["default"](m.ASINS_INFO).data("asinsinfo"))&&void 0!==e?e:{});e=null!==(c=d["default"](m.CONTENT_TITLE).text())&&void 0!==c?c:"";c=null!==(b=d["default"](m.COUNTRY_CODE).text())&&void 0!==b?b:"";b=null!==(g=d["default"](m.COUNTRY_NAME).text())&&void 0!==g?g:"";var t=O();if(t){var x=f?h.MOBILE_POSTFIX:"";k.count(h.GET_CONTENT+x,1);a({asinsInfo:p,contentTitle:e,countryCode:c,countryName:b},
function(q,n){k.count(h.CONTENT_SUCCESS+x,1);P(q,t,f);null===n||void 0===n?void 0:n()},function(q,n){k.count(h.CONTENT_FAILURE+x,1);switch(t){case r.DETAIL_UNDELIVERABLE:d["default"](z.DISABLED_ATC).removeClass(y.AOK_HIDDEN)}null===n||void 0===n?void 0:n()})}},R=function(a,f){var e=f?h.MOBILE_POSTFIX:"",c=0;d["default"](".export-alternative-cta").each(function(b,g){c++;b=d["default"](g).children(":first");var p=b.data("asin"),t=b.data("offerlistingid");p&&t&&d["default"](g).click(function(){k.count(h.ATC_CLICK+
e,1);a({asin:""+p,offerListingId:""+t},function(x,q){k.count(h.ATC_SUCCESS+e,1);null===q||void 0===q?void 0:q();"app"===x.context.deviceSubType?location.replace("/gp/cart/view.html"):location.reload()},function(x,q){k.count(h.ATC_FAILURE+e,1);null===q||void 0===q?void 0:q()})})});k.count(h.ITEM_COUNT+"_"+c,1);d["default"](".export-alternative-product-link").each(function(b,g){return d["default"](g).click(function(){return k.count(h.ITEM_CLICK+e,1)})})},I={},D=function(a,f,e){void 0===f&&(f="");void 0===
e&&(e=1);f=a+f;I.hasOwnProperty(f)||(I[f]=!0,k.count(a,(k.count(a)||0)+e))},S=function(a){D(v["default"].capabilities.mobile?"Card:EERU:SharedLib:mobile:render":"Card:EERU:SharedLib:desktop:render");var f=function(c,b){c={$event:{preventDefault:v["default"].$.noop,stopPropagation:v["default"].$.noop},$target:c.getContent().find('[data-a-tab-name="'+b+'"]'),data:{name:"energyEfficiencyTabSet"}};v["default"].trigger("a:declarative:a-tabs:click",c)},e=function(c,b){var g=c&&c.$event,p=c&&c.data||{},
t=p.activeTabName,x=p.modalHeight,q=p.name;g&&g.preventDefault&&g.preventDefault();g&&g.stopPropagation&&g.stopPropagation();g=b.get(q);g||(v["default"].on("a:popover:beforeShow:"+q,function(n){n.popover&&n.popover.getContent&&(n=n.popover.getContent(),n.find(".a-manually-loaded").parent().css("min-height",x),v["default"].loadDescendantImagesManually(n))}),g=b.create(c.$target,p));g.show();f(g,t)};a.when("a-secondary-view").execute("RegisterEnergyEfficiencyEventMobile",function(c){v["default"].declarative("card-energy-efficiency-secondary-view",
"click",function(b){D("Card:EERU:SharedLib:mobile:click",b&&b.data&&b.data.name||"");e(b,c)})});a.when("a-modal").execute("RegisterEnergyEfficiencyEventDesktop",function(c){v["default"].declarative("card-energy-efficiency-modal","click",function(b){D("Card:EERU:SharedLib:desktop:click",b&&b.data&&b.data.name||"");e(b,c)})})},T=function(a){a.when("ready").execute("EEBadgeProductFicheResize",function(f){var e=v["default"].$;e(".energyEfficiencyContainer").each(function(c,b){c=e(b).find(".energyEfficiencyProductFicheLabel").first();
b=e(b).find("svg").first();c.parent().outerHeight()>b.outerHeight()&&(c.removeClass("a-size-small"),c.addClass("a-size-micro"),c.parent().outerHeight()>b.outerHeight()&&c.parent().css("line-height","10px"))})})},U=function(){var a=window.P;S(a);T(a)};E._operationNames=["getContent","addToCart"];E.card=function(){return F.__awaiter(void 0,void 0,void 0,function(){var a,f,e;return F.__generator(this,function(c){U();a=M["default"].setup();f=function(b,g,p){J.addTracking(a.addToCart,{},"ex_alt_wg_atc_d")(b).then(g).catch(p)};
e=function(b,g,p){a.getContent(b).then(function(t){return g(t,function(){return R(f,!1)})}).catch(p)};Q(e,!1);return[2]})})}});
